<p>
  <a href="https://twitter.com/intent/follow?screen_name=fbjest"><img align="left" src="https://img.shields.io/twitter/follow/vishalm84.svg?style=social&label=Follow%20@vishalm84" alt="Follow on Twitter"></a>
<br />
</p>

[![Travis](https://travis-ci.org/vishalm/behave_parallel_demo.svg)](https://travis-ci.org/vishalm/behave_parallel_demo)


language: python
sudo: false
python:
  - "2.7"
cache:
  directories:
    - $HOME/.env/pip
script:
  - python --version
  - pip install virtualenv
  - virtualenv .env
  - source .env/bin/activate
  - pip install -r requirements.txt
  - pip install git+git://github.com/hugeinc/behave-parallel.git@a57eff3087aae9bd7519a7d4fc15228611db20b9#egg=behave-parallel --upgrade
  - pip freeze
  - behave --processes 5 --parallel-element feature
