language: python
sudo: false
python:
  - "2.7"
cache:
  directories:
    - $HOME/.env/pip
script:
  - python --version
  - pip install virtualenv
  - virtualenv .env
  - source .env/bin/activate
  - pip install -r requirements.txt
  - pip install git+git://github.com/hugeinc/behave-parallel.git@a57eff3087aae9bd7519a7d4fc15228611db20b9#egg=behave-parallel --upgrade
  - pip freeze
  - behave --processes 5 --parallel-element feature
